[package]
name = "AoC2022_01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day01_part1"
path = "src/part1.rs"

[[bin]]
name = "day01_part2"
path = "src/part2.rs"

